name: CI

on: [push, pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9

    - name: Install dependencies for linting and static analysis
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint and static analysis
      run: |
        flake8

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        flake8
